home/urls.py
from django.urls import path
from . import views

app_name = 'inicio_app'


urlpatterns = [
    path('', views.homeview, name='inicio' ),
    path('perfil/<username>/', views.perfil, name='profile'),
    path('solicitudes/', views.friend_views, name="friend"),
    path('perfil-setting/', views.perfil_setting_views, name="perfil-setting"),
    path('perfil-photos/<username>/', views.fotos_views, name="perfil-photos"),
    path('perfil-about/<username>/', views.about_views, name="perfil-about"),
    path('buscar-contenido/', views.buscar_contenido_views, name="buscar-contenido"),
    path('agreagr-like-status/<pk>/', views.agergar_like_status, name="agregar-like"),
    path('enviar-solicitud/<username>/', views.enviar_solicitud, name="enviar-solicitud"),
    path('agregar-amigos/<username>/', views.añadir_a_amigos, name="agregar-amigos"),
    path('friend-añadidos/', views.amigos_añadidos, name="friend-añadidos"),
    path('chat-usuario/<username>/', views.chats_usuarios, name="chat-usuario"),
    path("ultimo-chat/", views.ultimos_chats, name="ultimo-chat"),
    path('listar-notificaciones/', views.listar_notificaciones, name="listar-notificaciones"),
    path("Settings/", views.Settings_views, name="Settings"),
    path("feed/<pk>/", views.feed_views, name="feed"),
    path("compartir-post/<pk>/", views.compartir_post, name="compartir-post"),
    path('sugerencia-amigo/', views.sugerencias_amigos_views, name="sugerencia-amigo"),
    path('comentar-post-profile/<pk>/',  views.comentar_post, name="comentar-post-profile" ),
    path('eliminar-post/<pk>/', views.eliminar_post, name="eliminar-post"),
    path('eliminar-conpartido/<pk>/', views.eliminar_conpartidos, name="eliminar-conpartido")
    # path('cambiar-perfil/', views.cambiar_perfil, name="cambiar-perfil")
    #path('cambiar-contraseña/', views.cambiar_contraseña, name="cambiar-contraseña"),
    

]

socialapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static, serve
#from .views import media
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('reymanueladmin010899/', admin.site.urls),
    path('inicio/', include('home.urls', namespace='inicio_app')),
    path('', include('users.urls', namespace='users_app')),
    #path('media/<str:path>/', media, name='media'),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users_app'

urlpatterns = [
    path('registrar/', views.registrar_usuario, name='registrar'),
    path('', views.iniciar_secion, name='iniciar-secion'),
    path('logout/', views.logoutviews, name="logout"),
    path('verificar-codigo/<username>', views.verificar_codigo, name="verificar_codigo")
]

home/forms.py
from django.forms import ModelForm
from django import forms
from users.models import User
from django.forms import ClearableFileInput

class  userupdateavatar(ModelForm):
    class Meta:
        model=User
        fields = ('avatar',)
       
    
    

home/views.py
from django.shortcuts import render, redirect
from .funciones import actualizarperfil,agregar_like_publicaciones,si_tu_like_existe, solicitud_enviada
from django.contrib.auth.decorators import login_required
from users.models import User
from .models import PostModel, LikeModels, SolisitudMOdel, ChatVistoModels,  AmigoModels, NotificacionesModels, ChatModels, ComentarModels, ConpartirModels, ComentarioLike
from users.models import InformacionPersonal
from django.db.models import Count,Q
from django.core.paginator import Paginator
from .context_processors import validar_amigo
from django.contrib.auth import logout, authenticate
from .forms import  userupdateavatar


@login_required(login_url='users_app:registrar')
def homeview(request):
    #activo = seciones_activas(request)
    usuario = User.objects.get(username=request.user.username)
    agregar_like_publicaciones(request)
    post_comentario = PostModel.objects.all().order_by("-created")
    existe = si_tu_like_existe(request,post_comentario)
    cant_amigos = AmigoModels.objects.filter(user=request.user).count()
    cant_like, cant_post = PostModel.objects.camtidades(usuario) 
    notificaciones = NotificacionesModels.objects.notificaciones(request.user).order_by('-created')[:5]
    uugerensias = AmigoModels.objects.sugerencias_amigos(request.user)
    sugerencia = User.objects.filter(id__in=uugerensias)[:5]
    usuarios_activos = AmigoModels.objects.filter(user=request.user,  añadidos__is_online=True)[:10]
    if request.method == 'POST':
        contenido = request.POST.get('status','')
        archivo = request.FILES.get('files','')
        if contenido != '' or archivo != '': 
            PostModel.objects.create(user=request.user, archivo=archivo,   descripcion=contenido)
    return render(request, 'index.html', {'posts':post_comentario,'notificaciones':notificaciones, "sugerencia":sugerencia,'usuarios_activos':usuarios_activos,'cantidad_conectados':usuarios_activos.count(),   })





@login_required(login_url='users_app:registrar')
def  perfil(request, username):
    user = request.user
    usuario = User.objects.get(username=username)
    cant_amigos = AmigoModels.objects.filter(user=usuario).count()
    cant_like, cant_post = PostModel.objects.camtidades(usuario) 
    amigo_o_no=validar_amigo(usuario, user)
    solicitud = solicitud_enviada(usuario, user)
    id_post = request.GET.get("like",'')
    if id_post != '':
        agregar_like_publicaciones(request)
    if request.method == "POST":
        contenido = request.POST.get('status','')
        archivo = request.FILES.get('files')
        if contenido and archivo:
            PostModel.objects.create(user=user, archivo=archivo,   descripcion=contenido)
        elif contenido or archivo:
            PostModel.objects.create(user=user, archivo=archivo, descripcion=contenido)
      
       
    status = PostModel.objects.filter(user__username=username).order_by('-created')
    ultimas_fotos = PostModel.objects.ultimas_fotos(usuario).order_by('-created')[:10]
    amigos_comun = AmigoModels.objects.obtener_amigos_en_comun(usuario, user )[:5]
    notificaciones= NotificacionesModels.objects.notificaciones(request.user)[:5]
    compatido =  ConpartirModels.objects.compartidos(usuario) 
    usuarios_activos = AmigoModels.objects.filter(user=request.user,  añadidos__is_online=True)[:10]
    return render(request , 'profile.html',{"estados":status, 'usuario':usuario, 'ultimas':ultimas_fotos,
                                             'comunes':amigos_comun, 'numero':len(amigos_comun),
                                               'notificaciones':notificaciones, 'amigo_o_no':amigo_o_no,
                                                 'cantidad_like':cant_like,'cantidad_post':cant_post,
                                                   'cantidad_amigos':cant_amigos, 'compartidos':compatido,
                                                     'usuarios_activos':usuarios_activos, 'cantidad_conectados':usuarios_activos.count(),
                                                      'enviada':solicitud})




@login_required(login_url='users_app:registrar')
def friend_views(request):
    solicitudes = SolisitudMOdel.objects.filter(solisitud=request.user).exclude(user=request.user)
    return render(request, "friends.html", {'usuarios':solicitudes})




def perfil_setting_views(request):
    user_perfile =  User.objects.get(username=request.user.username)
    form = userupdateavatar(instance=user_perfile,  initial={"avatar":None, "Currently":None})
    if request.method == "POST":
        nombres = request.POST.get('nombre','')
        if nombres != '':
            actualisado = actualizarperfil(request)
            if actualisado is not None:
                return redirect('inicio_app:perfil-about', username=actualisado.username)

        form = userupdateavatar(request.POST, request.FILES, instance=user_perfile, initial={'avatar':None})
        if form.is_valid():
            form.save()
            return redirect('inicio_app:inicio')
       
    return  render(request , 'perfil.html', {'form':form})



# @login_required(login_url='users_app:registrar')
# def  perfil_setting_views(request):
#     if request.method == 'GET':
#         return render(request , 'perfil.html')
#     else:        
       



@login_required(login_url='users_app:registrar')
def fotos_views(request, username):
    if request.method == "GET":
        usuario = User.objects.get(username=username)
        cant_amigos = AmigoModels.objects.filter(user=usuario).count()
        cant_like, cant_post = PostModel.objects.camtidades(usuario) 
        user=request.user
        amigo_o_no=validar_amigo(usuario, user)
        fotos =  PostModel.objects.filter(user__username=username).order_by("-created")
    return render(request, "photos.html",{'fotos':fotos,'usuarios':usuario, 'amigo_o_no':amigo_o_no, 'nun_post':cant_post, 'nun_like':cant_like, 'nun_amigo':cant_amigos})




@login_required(login_url='users_app:registrar')
def about_views(request, username):
    usuario = User.objects.get(username=username)
    cant_amigos = AmigoModels.objects.filter(user=usuario).count()
    cant_like, cant_post = PostModel.objects.camtidades(usuario) 
    user=request.user
    amigo_o_no=validar_amigo(usuario, user)
    amigos_comun = AmigoModels.objects.obtener_amigos_en_comun(usuario, user )[:5]
    ultimas_fotos = PostModel.objects.ultimas_fotos(usuario).order_by('-created')[:10]
    personal = InformacionPersonal.objects.filter(user__username=username).first()
    if personal:
        return render(request, "about.html", {'personal':personal,'persona':usuario, 'cantidad_amix':cant_amigos, 'cantidad_pots':cant_post,'cantidad_like':cant_like,  'amigo_o_no':amigo_o_no, 'usuario':usuario, 'fotos':ultimas_fotos, 'amigos':amigos_comun})
    return redirect('inicio_app:perfil-setting')


@login_required(login_url='users_app:registrar')
def buscar_contenido_views(request):
        agregar_like_publicaciones(request)
        post_comentario = PostModel.objects.all().order_by("-created")
        existe = si_tu_like_existe(request,post_comentario)
        notificaciones = NotificacionesModels.objects.notificaciones(request.user).order_by('-created')[:5]
        uugerensias = AmigoModels.objects.sugerencias_amigos(request.user)
        sugerencia = User.objects.filter(id__in=uugerensias)[:4]
        usuarios_activos = AmigoModels.objects.filter(user=request.user,  añadidos__is_online=True)[:10]
        if request.method == 'POST':
            contenido = request.POST.get('status','')
            archivo = request.FILES.get('files','')
            if contenido != '' or archivo != '':
                PostModel.objects.create(user=request.user, archivo=archivo,   descripcion=contenido)
                return redirect('inicio_app:inicio')
            return redirect('inicio_app:inicio')
        else:
            contenido = request.GET.get('buscar','')
            if contenido != '':
                resulatdo = User.objects.filtrar_contenido(contenido)
                publicaciones = PostModel.objects.filter(descripcion__icontains=contenido) 
                return render(request, 'contenido.html',{'encontrados':resulatdo,'publicaciones':publicaciones,'existe':existe, 'notificaciones':notificaciones, "sugerencia":sugerencia,'usuarios_activos':usuarios_activos,'cantidad_conectados':usuarios_activos.count()})
            return render(request, 'contenido.html',{'existe':existe, 'notificaciones':notificaciones, "sugerencia":sugerencia,'usuarios_activos':usuarios_activos,'cantidad_conectados':usuarios_activos.count()})




@login_required(login_url='users_app:registrar')
def agergar_like_status(request, pk):
    statud = PostModel.objects.get(id=pk)
    if statud:
       obj, cred = LikeModels.objects.get_or_create(post=statud, user=request.user)
       if cred:
            return redirect('inicio_app:profile', username=statud.user.username)
       else:
            obj.delete()
            return redirect('inicio_app:profile', username=statud.user.username)
   



@login_required(login_url='users_app:registrar')
def enviar_solicitud(request, username):
    if username is not None:
        usuario =  User.objects.get(username=username)
        obj, cred = SolisitudMOdel.objects.get_or_create(solisitud=usuario,  user=request.user)
        return redirect('inicio_app:profile', username=username)
    


@login_required(login_url='users_app:registrar')
def añadir_a_amigos(request, username):
    if username is not None:
        usuario =  User.objects.get(username=username)
        obj, cred=AmigoModels.objects.get_or_create(añadidos=usuario, user=request.user)
        if cred:
            AmigoModels.objects.create(user=usuario, añadidos=request.user)
            solicitud = SolisitudMOdel.objects.get(user__username=username)
            solicitud.delete()
            return redirect('inicio_app:friend')
        else:

home/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="right_row">
    <div class="row border-radius">
        <div class="feed">
            <div class="feed_title">
                <span><a href="  {% url 'inicio_app:profile' personal.user.username  %} "><b>Profile</b></a> | <a href=" {% url 'inicio_app:perfil-about' personal.user.username %}" id="select_profile_menu"><b>About</b></a> |  <a href="{% url 'inicio_app:perfil-photos' personal.user.username %} "><b>Photos</b></a>  {% if user.id != usuario.user.id %} 
                    {% if amigo_o_no %}
                    <a href=" {% url 'inicio_app:chat-usuario' usuario.username %} " id="select_profile_menu"><b>| Chat</b></a></span>
                    {% else %}
                   
                    {% endif %}
                    {% else%}
                    <a href=" {% url 'inicio_app:enviar-solicitud' usuario.username %} " id="select_profile_menu"><b>Enviar Solicitud</b></a></span>
                    {% endif %}
            </div>        
        </div>
    </div>
    <div class="row border-radius">
        <div class="settings shadow">
            <div class="settings_title">  
                <h3>Personal Info</h3>
            </div>
            <div class="settings_content">
                <style type="text/css">
                    .settings_content ul li p {padding:5px;padding-left: 20px}
                </style>
                <ul>
                    <li>
                        <p>
                            <b>About Me:</b>
                            <br>
                            <span>{{personal.descripcion}}</span>
                        </p>
                    </li>
                    <li>
                        <p>
                            <b>Birthday:</b>
                            <br>
                        </p>
                    </li>
                   <p style="margin-left: 20px;">{{personal.birthday}}</p> 
                    <li>
                        <p>
                            <b>pais:</b>
                            <br>
                            {{personal.pais}}
                        </p>
                    </li>
                    <li>
                        <p>
                            <b>provincia:</b>
                            <br>
                            {{personal.estado}}
                        </p>
                    </li>
                  
                   
                    <li>
                        <p>
                            <b>Email:</b>
                            <br>
                            {{personal.user.gmail}}
                        </p>
                    </li>
                    <li>
                        <p>
                            <b>Website:</b>
                            <br>
                            <a href="{{personal.webside}}">{{personal.webside}}</a>
                        
                        </p>
                    </li>
                    <li>
                        <p>
                            <b>Phone Number:</b>
                            <br>
                            {{personal.telefono}}
                        </p>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="suggestions_row">
    <div class="row shadow">
        <div class="row_title">
            <span>Last photos</span>
            <a href="{% url 'inicio_app:perfil-photos' personal.user.username %} ">see all..</a>
        </div>
        <div class="row_contain_profilephotos">
            <ul>
                {% for ultima in fotos %}
                {% if ultima.images %}
                <li><a href="{% url 'inicio_app:feed' ultima.id %}"><img src="{{ultima.archivo.url}}" alt="" /></a></li>
                {% elif ultima.video %}
                
                {% endif %}             
                {% endfor %}                       
            </ul>
        </div>
    </div>
    <div class="row shadow">
        <div class="row_title">
            {% if user.id != personal.id %}
            <span>Amigos </span>
            <a href="{% url 'inicio_app:friend-añadidos' %}"> + {{totalamigos}} more..</a>
            {% else %}
            <h4>info personales</h4>
            {% endif %}
        </div>
        {% for comun in amigos %}
        <div class="row_contain">
            <img src="{{comun.añadidos.avatar.url}} " alt="" />   
            <span><a href="{% url 'inicio_app:perfil-about' comun.añadidos.username %} ">{{comun.añadidos.username}} </a><br></span>
            <button>+</button>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock content %}

home/templates/profile.html
{% extends 'base.html' %}
{% block content %}

        <div class="right_row">
            <div class="row border-radius">
                <div class="feed">
                    <div class="feed_title">
                        <span><a href=" {% url 'inicio_app:profile' usuario.username %} " id="select_profile_menu"><b>Profile</b></a> |  <a href="{% url 'inicio_app:perfil-about' usuario.username %}"><b>About</b></a> | <a href="{% url 'inicio_app:perfil-photos' usuario.username %}  "><b>Photos</b></a>  {% if user.id != usuario.id %}  |
                            {% if amigo_o_no %}
                            <a href=" {% url 'inicio_app:chat-usuario' usuario.username %} " id="select_profile_menu"><b>Chat</b></a></span>
                            
                            {% else %}
                                {% if enviada %}
                                    <a href="" id="select_profile_menu"><b>solicitud enviada</b></a></span>
                                {% else %}
                                    <a href=" {% url 'inicio_app:enviar-solicitud' usuario.username %} " id="select_profile_menu"><b>Enviar Solicitud</b></a></span>
                                {% endif %}
                            {% endif %}
                            {% else %}
                            {% endif %} 
                            
                    </div>
                </div>
            </div>

            {% if user.id == usuario.id %}
            <div class="row">
                <div class="publish">
                    <div class="row_title">
                        <span><i class="fa fa-newspaper-o" aria-hidden="true"></i> Status</span>
                    </div>
                    <form method="POST" enctype="multipart/form-data" >{% csrf_token %}
                        <div class="publish_textarea">
                            <img class="border-radius-image" src=" {{usuario.avatar.url}}" alt="" />
                            <textarea  name="status"  type="text" placeholder="¿Whats up, {{user.username}} ?" style="resize: none;"></textarea>
                        </div>
                        <div class="publish_icons">
                            <ul> <input  type="file" name="files" id=""></a></i></li>

                            </ul>
                            <button>Publish</button>
                        </div>
                    </form>
                </div>
            </div>
            {% else %}
            {% endif %}
            {% for stat in  compartidos %}
            <div class="row border-radius">
                {% if stat.amigo.añadidos == user %}
                <span style="margin-left: 98%;"><a href="{% url 'inicio_app:eliminar-conpartido' stat.id %} ">x</a></span>
                {% endif %}
              
                <div class="feed">
                    <div class="feed_title">
                        <img src="{{stat.user.avatar.url}} " alt="" />
                         <span><a href="{% url 'inicio_app:profile' stat.user.username %} "><b>{{stat.user.username}}</b></a> Compatio  -> <span style="color: blue;">{{stat.amigo.añadidos.username}}</span></span>
                    </div>                     
                    <div class="feed_content">
                        <span style="margin-left: 30px;"> {{stat.post.descripcion}}</span>  
                        {% if stat.post.images %}
                        <div class="feed_content_image">                                                              
                            <a href="{% url 'inicio_app:feed' stat.post.id %} "><img src="{{stat.post.archivo.url}} " alt="" /></a>                           
                        </div>
                        {% elif stat.post.video %}
                        <div class="row border-radius">
                            <div class="feed">
                                <div class="feed_content">
                                    <div class="feed_content_image">
                                        <video src=" {{stat.post.archivo.url}}"  style="height: 200px; width: 100%;" controls="controls" class="card-img-top" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}                                 
                    </div>
                    <div class="feed_footer">
                        <ul class="feed_footer_left">
                            <li class="hover-orange selected-orange"><a  href="?like={{stat.post.id}}" ><i class="fa fa-heart"></i></a></li>
                            <li>{{stat.post.like_post_reverse.count}}</li>
                        </ul>
                        <ul class="feed_footer_right">
                            <li>
                                <li class="hover-orange selected-orange"><a href="{% url 'inicio_app:compartir-post' stat.post.id %} "><i class="fa fa-share"></i>{{stat.post.concartir_post_riverse.count}}</li></a>
                               <li><a href= "{% url 'inicio_app:feed' stat.post.id %} " style="color:#515365;"><li class="hover-orange"><i class="fa fa-comments-o"></i> {{stat.post.comentario_post_reverse.count}} comments</li></a></li> 
                                
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            
        {% endfor %}

            {% for stat in estados  %}
      
            <div class="row border-radius">
                {% if stat.user == user %}
                <span style="margin-left: 98%;"><a href="{% url 'inicio_app:eliminar-post' stat.id %} ">x</a></span> 
                {% endif %}

                <div class="feed">
                    <div class="feed_title">
                        <img src="{{usuario.avatar.url}} " alt="" />
                        <span><b>{{usuario.username}}</b> Created -> <br><p>{{stat.creado}}</p></span>
                        {{stat.created}}
                    </div>
             
                    <div class="feed_content">
                        {% if stat.images %}
                        <div class="feed_content_image">
                            {% if stat.descripcion %}
                            {{stat.descripcion|truncatechars:100}}
                            {% endif %}
                            <a href="{% url 'inicio_app:feed' stat.id %} "><img style="max-height: 400px;" src="{{stat.archivo.url}} " alt="" /></a>
                        </div>
                        {% elif stat.video %}
                        <div class="row border-radius">
                            <div class="feed">
                                <div class="feed_content">
                                    <div class="feed_content_image">
                                        <video src=" {{stat.archivo.url}}"  style="height: 200px; width: 100%;" controls="controls" class="card-img-top" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% elif stat.descripcion %}
                        {% if not stat.images %}
                        {% if not stat.video %}
                        {% if not stat.archivo %}
                        <div class="feed_content_image">
                        {{stat.descripcion}}
                        </div>
                        {% endif %}                                  
                        {% endif %}                                 
                        {% endif %}
                        {% endif %}                     
                    </div>
                    <div class="feed_footer">
                        <ul class="feed_footer_left">
                            <li class="hover-orange selected-orange"><a  href="{% url 'inicio_app:agregar-like' stat.id  %} "><i class="fa fa-heart"></i></a>{{stat.like_status_reverse.count}}</li>
                            <li> {{stat.like_post_reverse.count }}</li>
                           
                        </ul>
                        <ul class="feed_footer_right">
                            <li>
                                <li class="hover-orange selected-orange"><a href="{% url 'inicio_app:compartir-post' stat.id %}"><i class="fa fa-share"></i>{{stat.concartir_post_riverse.count}} </li></a>
                               <li><a href=" {% url 'inicio_app:feed' stat.id %}" style="color:#515365;"><li class="hover-orange"><i class="fa fa-comments-o"></i> {{stat.comentario_post_reverse.count}} comments</li></a></li>
                                
                            </li>
                        </ul>
                    </div>
                   
                </div>
            </div>
            {% endfor %}
        

            <center>
                <a href=""><div class="loadmorefeed">
                    <i class="fa fa-ellipsis-h"></i>
                </div></a>
            </center>
        </div>

        <div class="suggestions_row">
            

            <div class="row shadow">
                <div class="row_title">
                    <span>Ultimas Fotos</span>
                    <a href="{% url 'inicio_app:perfil-photos' usuario.username %} ">see all..</a>
                </div>
                <div class="row_contain_profilephotos">
                    <ul>
                        {% for ultima in ultimas  %}
                        {% if ultima.images %}
                            <li><a href="{% url 'inicio_app:feed' ultima.id %} "><img src="{{ultima.archivo.url}} " alt="" /></a></li>
                        {% endif %}
                        
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row shadow">
                <div class="row_title">
                    <span>Conectados..   + {{cantidad_conectados}} </span>
                </div>
                {% for activos in  usuarios_activos %}
                <div class="row_contain">
                    <img src="{{activos.añadidos.avatar.url}} " alt="" />
                    <span><a href="{% url 'inicio_app:chat-usuario' activos.añadidos.username %} " class="selected-orange">{{activos.añadidos.username}}</a><span><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentCol" style="background-color: rgb(47, 240, 21); border-radius:15px;  margin-left:100% ;"   viewBox="0 0 0 16">
                        <path d="M8 12a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0 1A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"/>
                      </svg></span></span>
                </div>
                {% endfor %}
            </div>
            <div class="row shadow">
                <div class="row_title">
                    {% if user.id == usuario.id %}
                    <span>Amigos </span>
                    <a href="{% url 'inicio_app:friend-añadidos' %}"> + {{totalamigos}} more..</a>
                    {% else %}
                    <span>Amigos en comun</span>
                    {% endif %}
                </div>
                {% for comun in comunes %}
                
                <div class="row_contain">
                    <img src="{{comun.añadidos.avatar.url}} " alt="" />   
                    <span><a href="{% url 'inicio_app:profile' comun.añadidos.username %} ">{{comun.añadidos.username}} </a><br></span>
                    <button>+</button>
                </div>

                {% endfor %}
            </div>

            <div class="row shadow">
                <div class="row_title">
                    <span>Actividades reciente</span>
                </div>

                {% for noti in notificaciones %}
                    {% if noti.solicitud %}
                        <div class="row_contain">
                            <img src="{{noti.solicitud.user.avatar.url}} " alt="" />
                            <span><a href="{% url 'inicio_app:agregar-amigos' noti.solicitud.user.username %} " class="selected-orange">{{noti.mensaje}} </a>..</span>
                        </div>
                    {% elif noti.comentarios.user.id == user.id %}
                    
                    {% elif noti.amigo %}
                    <div class="row_contain">
                        <img src="{{noti.amigo.añadidos.avatar.url}} " alt="" />
                        <span><a href="{% url 'inicio_app:chat-usuario' noti.amigo.añadidos.username %} " class="selected-blue">{{noti.mensaje}}</a>..</span>
                    </div> 
                    {% elif noti.like %}
                    <div class="row_contain">
                        <img src="{{noti.like.user.avatar.url}} " alt="" />
                        <span><a href=" {% url 'inicio_app:feed' noti.like.post.id %} " class="selected-blue">{{noti.mensaje|truncatechars:50}}</a>..</span>
                    </div>
                    
                    {% elif noti.comentarios %}
                    <div class="row_contain">
                        <img src="{{noti.comentarios.user.avatar.url}} " alt="" />
                        <span><a href="{% url 'inicio_app:feed' noti.comentarios.post.id %} " class="selected-blue">{{noti.mensaje|truncatechars:50}}</a>..</span>
                    </div>

                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    {% endblock content %}